[package]
name = "mbedtls-sys-auto"
version = "2.25.0"
authors = ["Jethro Beekman <jethro@fortanix.com>"]
build = "build/build.rs"
license = "Apache-2.0/GPL-2.0+"
#edition = "2018"
description = """
Rust bindings for MbedTLS.

This version generates the correct bindings at compile time using bindgen."""
readme = "../README.md"
repository = "https://github.com/fortanix/rust-mbedtls"
documentation = "https://docs.rs/mbedtls-sys-auto/"

[lib]
name = "mbedtls_sys"

[dependencies]
libc = { version = "0.2.0", optional = true }
libz-sys = { version = "1.0.0", optional = true }

[build-dependencies]
bindgen = "0.19.0"
cmake = "0.1.17"

[features]
# If you use mbedtls-sys in a no_std configuration, you need to provide your
# own versions of the following functions:
#
# * calloc/free
# * strstr/strlen/strncpy/strncmp/strcmp/snprintf
# * memmove/memcpy/memcmp/memset
# * rand/printf (used only for self tests. optionally use custom_printf)
default = ["std", "zlib", "time", "pthread", "aesni", "padlock", "legacy_protocols"]
std = []
custom_printf = []
custom_time = ["custom_gmtime_r", "time"]
custom_gmtime_r = ["time"]
custom_has_support = []
aes_alt = []
custom_threading = ["threading"]
pthread = ["libc","threading"]
threading = []
time = []
havege = ["time"]
zlib = ["libz-sys"]
pkcs11 = []
aesni = []
padlock = []
legacy_protocols = []
mpi_force_c_code = []
trusted_cert_callback = []
